// 문제를 추가하거나 수정할 때 이 배열만 편집하면 됩니다.
// type: "ox" | "multiple" | "short", difficulty: "easy" | "hard"
export const questions = [
  { id: "easy-ox-01", difficulty: "easy", type: "ox", question: "장애인 편의시설은 장애인만 이용할 수 있도록 만들어진 시설이므로, 비장애인이 이용하는 것은 원칙적으로 금지된다.", answer: "X", hint: "편의시설의 목적과 이용 금지는 서로 다른 문제입니다.", explanation: "장애인 편의시설은 장애인의 이동과 시설 이용을 돕기 위해 설치되지만, 비장애인의 이용을 원칙적으로 금지하는 시설은 아닙니다." },
  { id: "easy-ox-02", difficulty: "easy", type: "ox", question: "선천적 장애인의 수보다 후천적 장애인의 수가 더 많다.", answer: "O", hint: "장애는 태어날 때뿐 아니라 질병이나 사고 등 삶의 과정에서도 발생합니다.", explanation: "우리나라 장애인의 장애 발생 원인은 후천적 원인이 큰 비중을 차지합니다. 장애는 누구에게나 삶의 과정에서 발생할 수 있습니다." },
  { id: "easy-ox-03", difficulty: "easy", type: "ox", question: "한국수어는 한국어를 손동작으로 표현한 단순한 제스처이다.", answer: "X", hint: "한국수어에는 한국어와 구별되는 고유한 문법과 체계가 있습니다.", explanation: "한국수어는 고유한 문법과 체계를 가진 언어이며, 대한민국 농인의 공용어입니다." },
  { id: "easy-ox-04", difficulty: "easy", type: "ox", question: "우리나라는 장애인 차별 철폐의 날을 지정하고 있다.", answer: "O", hint: "매년 4월 20일을 어떻게 부르고 기념하는지 떠올려보세요.", explanation: "4월 20일의 정부 공식 명칭은 ‘장애인의 날’이며, 장애인 인권 단체들은 이날을 ‘장애인 차별 철폐의 날’로 부르며 투쟁과 연대의 날로 기념합니다." },

  { id: "easy-multiple-02", difficulty: "easy", type: "multiple", question: "다음 중 법적으로 인정되는 장애 유형이 아닌 것은?", options: ["시각장애", "청각장애", "언어장애", "학습장애"], answer: "학습장애", hint: "장애인복지법의 법정 장애 유형에 별도로 포함되지 않은 항목을 찾아보세요.", explanation: "우리나라 「장애인복지법」에서 학습장애는 별도의 법정 장애 유형으로 분류되지 않습니다." },
  { id: "easy-multiple-03", difficulty: "easy", type: "multiple", question: "우리나라 전체 인구 대비 등록장애인의 비율은 약 몇 %일까요?", options: ["약 0.1%", "약 1%", "약 5%", "약 25%"], answer: "약 5%", hint: "등록장애인은 전체 인구 약 20명 중 1명에 해당합니다.", explanation: "보건복지부 통계에 따르면 2025년 말 기준 등록장애인은 2,627,761명으로 주민등록인구의 약 5.1%입니다." },
  { id: "easy-multiple-04", difficulty: "easy", type: "multiple", question: "상시 근로자 50명 이상의 기업에서 장애인을 일정 비율 이상 고용하도록 하는 제도는 무엇일까요?", options: ["장애인 의무고용제도", "장애인 상시고용제도", "장애인 무조건고용제도", "장애인 지원고용제도"], answer: "장애인 의무고용제도", hint: "사업주가 법으로 정해진 비율을 반드시 지켜야 한다는 뜻이 이름에 담겨 있습니다.", explanation: "일정 규모 이상의 사업주는 법정 의무고용률에 따라 장애인을 고용해야 합니다." },

  { id: "easy-short-01", difficulty: "easy", type: "short", question: "장애인의 권리와 존엄성을 보장하고, 장애를 이유로 한 차별을 금지하기 위해 제정된 대한민국의 법률은 무엇일까요?", answer: ["장애인차별금지법", "장애인 차별 금지법", "장애인차별금지 및 권리구제 등에 관한 법률"], displayAnswer: "장애인차별금지법", explanation: "장애인차별금지법은 장애를 이유로 한 차별을 금지하고 장애인의 권리를 구제하기 위한 법률입니다." },
  { id: "easy-short-02", difficulty: "easy", type: "short", question: "장애인과 함께 살아가기 위해 우리가 할 수 있는 배려 한 가지를 적어주세요.", answer: ["이동통로 막지 않기", "이동 통로 막지 않기", "장애인 편의시설 배려하기", "먼저 물어보기", "도움이 필요한지 먼저 물어보기"], acceptAnyNonEmpty: true, hint: "일상에서 누군가의 선택과 이동을 더 편하게 만들 수 있는 작은 행동을 떠올려보세요.", displayAnswer: "여러분이 적어준 다양한 배려가 모두 좋은 실천이 될 수 있어요!", explanation: "좋은 생각이에요! 당사자의 선택을 존중하고, 필요한 도움이 있는지 먼저 묻는 작은 실천들이 함께 살아가는 사회를 만듭니다." },
  { id: "easy-short-03", difficulty: "easy", type: "short", question: "휠체어 이용자가 건물에 들어갈 때 계단 대신 이용할 수 있는 이동시설은 무엇일까요?", answer: ["경사로", "램프"], displayAnswer: "경사로", explanation: "경사로는 휠체어 이용자 등이 높이 차이를 안전하게 이동할 수 있도록 돕는 시설입니다." },
  { id: "easy-short-04", difficulty: "easy", type: "short", question: "‘벙어리 장갑’의 차별적 표현을 대신할 수 있는 말 한 가지를 적어주세요.", answer: ["손모아장갑", "손 모아 장갑", "엄지장갑", "엄지 장갑", "네손가락장갑", "네 손가락 장갑", "집게장갑", "집게 장갑"], acceptAnyNonEmpty: true, hint: "장갑의 생김새나 손가락 모양을 있는 그대로 표현하는 새로운 이름을 생각해보세요.", displayAnswer: "손모아장갑, 엄지장갑, 네 손가락 장갑, 집게장갑 등 다양한 표현", explanation: "좋은 표현을 제안해주었어요! 특정 장애를 낮잡아 이르는 말 대신 장갑의 형태와 특징을 자연스럽게 설명하는 다양한 말을 사용할 수 있습니다." },
  { id: "easy-short-05", difficulty: "easy", type: "short", question: "장애인이나 고령자 등 사회적 약자가 살기 좋은 사회를 만들기 위해 물리적·제도적·심리적 장벽을 허물자는 운동 및 정책은 무엇일까요?", answer: ["배리어프리", "barrierfree", "배리어 프리"], displayAnswer: "배리어프리(Barrier-Free)", explanation: "배리어프리는 생활 속 여러 장벽을 없애 누구나 접근하고 참여할 수 있게 하자는 개념입니다." },

  { id: "hard-ox-01", difficulty: "hard", type: "ox", question: "장애인 근로자에 대한 차별금지 의무는 회사에만 적용되므로, 노동조합은 장애를 이유로 장애인 근로자의 노동조합 가입을 거부할 수 있다.", answer: "X", hint: "차별금지 의무가 사용자에게만 있는지, 노동조합에도 적용되는지 생각해보세요.", explanation: "장애인차별금지법은 사용자뿐 아니라 노동조합도 가입이나 조합원의 권리·활동에 차별을 두어서는 안 된다고 규정합니다." },
  { id: "hard-ox-02", difficulty: "hard", type: "ox", question: "선의로 돕는 행위라도 장애인 당사자의 동의 없이 휠체어를 밀거나 신체에 접촉하는 것은 차별이나 권리 침해에 해당할 수 있다.", answer: "O", hint: "도움의 의도뿐 아니라 당사자의 자기결정권도 중요합니다.", explanation: "도움을 제공할 때에도 당사자의 의사와 자기결정권을 존중해야 합니다. 먼저 필요한 도움이 있는지 물어보는 것이 좋습니다." },
  { id: "hard-ox-03", difficulty: "hard", type: "ox", question: "정당한 편의 제공에 지나치게 많은 비용이 들더라도 장애인에 대한 편의 제공을 거부할 수 없다.", answer: "X", hint: "법에는 ‘과도한 부담’처럼 예외로 인정될 수 있는 사정도 있습니다.", explanation: "정당한 사유 없는 거부는 차별이지만, 과도한 부담이나 현저히 곤란한 사정이 있는 경우에는 정당한 사유가 인정될 수 있습니다." },
  { id: "hard-ox-04", difficulty: "hard", type: "ox", question: "장애인 보조견은 위생상 문제 때문에 음식점에서 업주의 판단에 따라 출입을 거부할 수 있다.", answer: "X", hint: "보조견표지가 있는 보조견의 출입을 단순히 업주의 재량으로 정할 수 있을까요?", explanation: "보조견표지를 붙인 장애인 보조견의 출입은 정당한 사유 없이 거부할 수 없습니다. 감염·위생관리가 특별히 필요한 일부 공간은 예외일 수 있습니다." },
  { id: "hard-ox-05", difficulty: "hard", type: "ox", question: "길에서 시각장애인 안내견을 만나면 반갑게 인사하고 쓰다듬거나 간식과 물을 제공하면 좋다.", answer: "X", hint: "안내견은 지금 보행을 돕는 업무에 집중하고 있습니다.", explanation: "안내견을 쓰다듬거나 먹을 것을 주면 업무 집중을 방해할 수 있습니다. 도움이 필요해 보이면 당사자에게 먼저 물어보세요." },

  { id: "hard-multiple-01", difficulty: "hard", type: "multiple", question: "「장애인차별금지법」에서 차별행위가 ‘악의적’인지 판단할 때 법률에 명시된 고려사항이 아닌 것은?", options: ["차별의 고의성", "차별의 지속성 및 반복성", "차별 피해자에 대한 보복성", "차별행위자와 피해자의 경제적 능력"], answer: "차별행위자와 피해자의 경제적 능력", hint: "행위의 의도·반복·보복과 직접 관련이 없는 항목을 찾아보세요.", explanation: "고의성, 지속성·반복성, 보복성 등은 고려하지만 양측의 경제적 능력은 명시된 판단 요소가 아닙니다." },
  { id: "hard-multiple-02", difficulty: "hard", type: "multiple", question: "유엔 장애인권리협약 제정 과정과 장애인 권리운동에서 당사자의 직접 참여를 강조한 대표적인 슬로건은?", options: ["우리에 관한 것을 우리 없이 만들지 말라", "장애는 차별이 아닌 다름이다", "치료와 재활을 넘어 완전한 자립으로", "턱 없는 세상, 차별 없는 사회"], answer: "우리에 관한 것을 우리 없이 만들지 말라", hint: "영문 슬로건은 ‘Nothing About Us Without Us’입니다.", explanation: "‘Nothing About Us Without Us’는 장애인과 관련된 결정에 당사자가 참여해야 한다는 원칙을 담습니다." },
  { id: "hard-multiple-03", difficulty: "hard", type: "multiple", question: "장애를 바라보는 사회적 모델의 관점에 가장 가까운 것은?", options: ["비장애인의 지속적인 보호와 도움이 가장 중요하다.", "개인의 손상을 치료와 재활로 극복하는 것이 우선이다.", "장애인이 겪는 제약은 사회적·환경적 장벽에서 비롯된다.", "장애는 개인의 특성과 환경의 상호작용으로만 정의해야 한다."], answer: "장애인이 겪는 제약은 사회적·환경적 장벽에서 비롯된다.", hint: "문제의 원인을 개인의 몸이 아니라 사회가 만든 장벽에서 찾는 관점입니다.", explanation: "사회적 모델은 제약의 원인을 개인의 몸보다 물리적 환경, 제도, 정보 접근 제한, 편견 등 사회가 만든 장벽에서 찾습니다." },
  { id: "hard-multiple-04", difficulty: "hard", type: "multiple", question: "현행 편의시설 설치기준상 경사로의 기울기는 원칙적으로 얼마 이하이어야 할까요?", options: ["1/6", "1/8", "1/10", "1/12"], answer: "1/12", hint: "보기 중 가장 완만한 기울기를 골라보세요.", explanation: "경사로의 기울기는 원칙적으로 1/12 이하로 설치합니다." },
  { id: "hard-multiple-05", difficulty: "hard", type: "multiple", question: "다음 표현 중 장애차별적 표현은 몇 개일까요?\n장애를 앓다 / 장애학우 / 결정장애 / 가사를 절다 / 고능하다", options: ["4개", "3개", "2개", "1개"], answer: "4개", hint: "‘장애학우’는 장애 유무와 관계없이 학생에게 쓸 수 있는 표현인지 생각해보세요.", explanation: "‘장애학우’를 제외한 네 표현은 장애를 질병이나 부족함의 비유로 사용하거나 능력을 우열화할 수 있는 표현입니다." },

  { id: "hard-short-01", difficulty: "hard", type: "short", question: "장애인이 동등한 근로조건에서 직무를 수행하도록 사용자가 시설·장비의 설치 또는 개조 등 필요한 조치를 제공하는 것을 법률에서는 무엇이라고 할까요?", answer: ["편의제공", "편의 제공", "정당한편의제공", "정당한 편의 제공"], displayAnswer: "편의제공", explanation: "편의제공은 장애인이 다른 사람과 동등하게 일할 수 있도록 필요한 조정과 지원을 제공하는 것입니다." },
  { id: "hard-short-02", difficulty: "hard", type: "short", question: "모든 사람이 성별, 나이, 장애 유무와 관계없이 제품이나 공간을 처음부터 편리하고 안전하게 이용하도록 설계하는 원칙은 무엇일까요?", answer: ["유니버설디자인", "유니버설 디자인", "universaldesign", "보편적설계", "보편적 설계"], displayAnswer: "유니버설 디자인(Universal Design)", explanation: "유니버설 디자인은 처음부터 가능한 한 많은 사람이 이용할 수 있도록 제품과 환경을 설계하는 원칙입니다." },
  { id: "hard-short-03", difficulty: "hard", type: "short", question: "손상된 달팽이관의 기능을 우회해 전기 신호로 청신경을 직접 자극하는 청각 보조기기는 무엇일까요?", answer: ["인공와우", "인공 와우"], displayAnswer: "인공와우", explanation: "인공와우는 소리를 전기 신호로 바꾸어 청신경을 직접 자극하는 의료기기입니다." },
  { id: "hard-short-04", difficulty: "hard", type: "short", question: "영상의 표정, 몸짓, 배경, 장면 전환 등 시각적 정보를 음성으로 설명해 주는 서비스는 무엇일까요?", answer: ["화면해설", "화면 해설", "음성해설", "음성 해설"], displayAnswer: "화면해설", explanation: "화면해설은 영상의 주요 시각 정보를 음성으로 전달해 콘텐츠 이해를 돕습니다." },
  { id: "hard-short-05", difficulty: "hard", type: "short", question: "장애인의 권리를 당연한 보장으로 보지 않고 비장애인이 선의로 ‘주는’ 혜택처럼 여기는 관점을 ‘OO적 관점’이라고 합니다. 무엇일까요?", answer: ["시혜적관점", "시혜적 관점", "시혜"], displayAnswer: "시혜적 관점", explanation: "시혜적 관점은 권리를 동등하게 보장해야 할 문제를 호의나 동정의 대상으로 바라보는 관점입니다." },
];
